#!/usr/bin/perl

package Lyse::CONGENEAL;

use strict;
use warnings;
use Utility qw(:all);
use Data::Dumper;
use Ilmm;

# Not actually exporting anything
require Exporter;
our @ISA = qw(Exporter);
our %EXPORT_TAGS = ('all' => [qw()]);
our @EXPORT_OK = (@{$EXPORT_TAGS{'all'}});
our @EXPORT = qw();

# CVS VERSION INFORMATION (AUTOMAGICALLY GENERATED BY CVS)
'$Revision: 1.3 $'              =~ /^.Revision: (.*) \$/; our $REVISION   = $1;
'$Date: 2009/01/09 00:05:53 $'  =~ /^.Date: (.*) \$/;     our $CHECKED_IN = $1;
'$Author: scouras $'            =~ /^.Author: (.*) \$/;   our $AUTHOR     = $1;


############################################## DEFAULT CONFIGURATION

our %CONFIG_ANAL = (

  revision        => $REVISION,
  checked_in      => $CHECKED_IN,
  author          => $AUTHOR,

  subtype         => '',
  resolution      => 10,
  
  file_data       => 'congeneal_t.dat',
  reference       => 'min.pdb',
  overwrite_anal  => 0,
  overwrite_plots => 0,
  start_emphasis  => 20,
  final_emphasis  => 20,
  width           => 1024,
  height          => 768,
  
  is_plotted      => 0,
  wait_to_finish  => 1,
  queue           => 'opterons',
  #queue           => 'analysis',
  plot            => "/users/scouras/code/scouras/plot_congeneal",

);




######################################################### INITIALIZE

sub New {
  return bless {
    name => 'CONGENEAL',
    %CONFIG_ANAL,
  };
}

sub Initialize {
  my $CONFIG_ANAL = $_[0];
  
  my %CONFIG_GLOBAL = $_[1] ? %{$_[1]} : ();
  my $ANAL = { 
    %$CONFIG_ANAL, 
    %CONFIG_GLOBAL,
  };

  $ANAL->{'title'} = $CONFIG_ANAL->{'name'};
  if ( $ANAL->{'subtype'} ) { 
    $ANAL->{'title'} .= " $ANAL->{'subtype'}";
  }
  return bless $ANAL;
}




########################################################### GET JOBS

sub Get_Jobs {

  my $ANAL    = $_[0];
  my $ILMM    = $_[1];
  my $REGION  = $_[2];

  # ANAL only executes on whole molecules and the entire simulation
  if ( not defined $REGION->{'molecule'} ) { return }
  if ( not defined $REGION->{'index'   } ) { return }
  if ( $REGION->{'period'}               ) { return }


  # SET UP JOB
  my $job = Lyse::Job::new ( $ANAL, $ILMM, $REGION, $ANAL->{'title'} );
  $job->{'resolution' } = $ANAL->{'resolution'};
  $job->{'line'       } = "congeneal $REGION->{'index'} $ANAL->{'reference'}";
  $job->Add_Image($ANAL->{'title'}, $ANAL->{'file_data'});
  $job->Validate_Initial();
  
  if ( wantarray ) { return ($job) }
  else             { return [$job] }
}



###################################################### VALIDATE JOBS
sub Validate_Job {

  my $ANAL = $_[0];
  my $job  = $_[1];

  my $dir = $job->{'path_anal'};
  my $ILMM = $job->{'ilmm'};

  # Verify that dir and data files exist
  if ( $ANAL->{'overwrite_anal'}  ) { return (0, "forced overwrite" ) }
  my ($valid, $message);
  ($valid, $message) = 
    Lyse::Job::Basic_Data_Check($job->{'path_anal'}, $job->{'path_data'});
  return ($valid, $message) if not $valid;
  $job->{'status'}{'existing'} = 1;
  ($valid, $message) = 
    Lyse::Job::Basic_Data_Time_Check( $job->{'path_data'}, 
                                $ILMM->{'start_time'},
                                $ILMM->{'finish_time'},
                                $ANAL->{'resolution'},
                                $ANAL->{'leniency'},
                                $ANAL->{'rewind'},
                                 );
  return ($valid, $message) if not $valid;

  $job->{'status'}{'valid'} = 1;
  return 1;
}


1

